id: P005482
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 11:52:53.757459
source_metadata:
  id: bdr:W1KG22041
  title: བྱང་ཆུབ་སེམས་དཔའི་སྐྱེས་རབས་ཀྱི་ཆོས་ཀྱི་གཎྜི།
  author: ''
  volumes:
    5f8370522751413c9ede6ba2031fe5e1:
      image_group_id: I1KG22095
      title: ''
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
