id: ICEE9434E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:34:35+00:00'
last_modified: '2022-06-08T03:24:09.659136+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22041
  title: བྱང་ཆུབ་སེམས་དཔའི་སྐྱེས་རབས་ཀྱི་ཆོས་ཀྱི་གཎྜི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    56F8:
      image_group_id: I1KG22095
      title: ''
      total_pages: 74
      order: 1
      base_file: 56F8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
